name: tds-ai-data-science
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - pytest
  - pip:
      - ruff
      - black
      - pre-commit
