"""Emit docs/IMAGE_INDEX.md — every committed raster path for browsing previews."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "docs" / "IMAGE_INDEX.md"

EXTENSIONS = (".png", ".svg", ".jpg", ".jpeg", ".webp", ".gif")


SCAN_DIRS = (
    PROJECT_ROOT / "articles",
    PROJECT_ROOT / "docs",
)


def iter_image_paths() -> list[Path]:
    """Only portfolio paths (not local venvs, `_sources/`, or site-packages)."""
    paths: list[Path] = []
    for base in SCAN_DIRS:
        if not base.is_dir():
            continue
        for extension in EXTENSIONS:
            paths.extend(base.rglob(f"*{extension}"))
    paths = [path for path in paths if "__pycache__" not in path.parts]
    return sorted(paths, key=lambda p: str(p.relative_to(PROJECT_ROOT)).lower())


def main() -> None:
    grouped: defaultdict[str, list[Path]] = defaultdict(list)
    for path in iter_image_paths():
        relative = path.relative_to(PROJECT_ROOT)
        top = relative.parts[0] if relative.parts else ""
        grouped[top].append(path)

    lines: list[str] = [
        "# Image index",
        "",
        "Committed raster files under this repository (browse here when choosing "
        "figures or README previews). Generated by `make image-index`. "
        "Notebook-only figures may still exist inside `.ipynb` files and are "
        "not listed unless exported.",
        "",
        f"- **Total files:** {sum(len(v) for v in grouped.values())}",
        "",
        "## Layout note",
        "",
        "`docs/assets/` keeps a **small** curated set (README thumbnails + "
        "social banner + montage). Most plots live under "
        "`articles/<project>/figures/`.",
        "",
    ]

    section_order = sorted(grouped.keys())
    for section in section_order:
        lines.append(f"## `{section}/`")
        lines.append("")
        for path in grouped[section]:
            relative = path.relative_to(PROJECT_ROOT).as_posix()
            lines.append(f"- `{relative}`")
        lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
